{% set name = "pi-vae-pytorch" %}
{% set version = "1.0.0rc1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pi_vae_pytorch-{{ version }}.tar.gz
  sha256: 5ed240208ba8b3fc848033900f50b22aa60d8ce5b31c6cd059567b0060e467a9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - pytorch

test:
  imports:
    - pi_vae_pytorch
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/mmcinnestaylor/pi-vae-pytorch
  summary: A Pytorch implementation of Poisson Identifiable VAE (pi-VAE), a variational auto encoder used to construct latent variable models of neural activity while simultaneously modeling the relation between the latent and task variables.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/mmcinnestaylor/pi-vae-pytorch
  doc_url: https://mmcinnestaylor.github.io/pi-vae-pytorch

extra:
  recipe-maintainers:
    - mmcinnestaylor
