{% set name = "pi-vae-pytorch" %}
{% set version = "1.0.0rc2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pi_vae_pytorch-{{ version }}.tar.gz
  sha256: 2d3f0c2e81dcdaf1eaadc4ad34b94f0c208978e713b06850834a6f279b66a5de

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - pytorch

test:
  imports:
    - pi_vae_pytorch
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/mmcinnestaylor/pi-vae-pytorch
  summary: A Pytorch implementation of Poisson Identifiable Variational Autoencoder (pi-VAE)
  description: Poisson Identifiable VAE (pi-VAE) is used to construct latent variable models of neural activity while simultaneously modeling the relation between the latent and task variables (non-neural variables, e.g. sensory, motor, and other externally observable states).
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/mmcinnestaylor/pi-vae-pytorch
  doc_url: https://mmcinnestaylor.github.io/pi-vae-pytorch

extra:
  recipe-maintainers:
    - mmcinnestaylor
